from docx import Document
from docx.shared import Inches

document = Document()

# header
section = document.sections[0]
header = section.header
p = header.paragraphs[0]
p.text = 'CV generated by James Brown. Generator made with Python by James Brown'

# profile picture
document.add_picture(
    'C:\\Users\\James Brown\\Downloads\\me.png', width=Inches(2.0), height=Inches(2.0)
)

# name phone number and email details
document.add_heading('Contact information')
name = input('What is your name? ')
phone_number = input('What is your phone number? ')
email = input('What is your email? ')

document.add_paragraph(
    f'{name} | {phone_number} | {email}')

# about me
document.add_heading('About me')
about_me = input('Tell me about yourself? ')
document.add_paragraph(about_me)

# work experience
document.add_heading('Work Experience')
p = document.add_paragraph()

company = input('Enter company ')
from_date = input('From Date ')
to_date = input('To Date ')

p.add_run(company + ' ').bold = True
p.add_run(from_date + '-' + to_date + '\n').italic = True

experience_details = input(
    'Describe what you did at ' + company + ' ')

p.add_run(experience_details)

# more work experiences
while True:
    has_more_experiences = input(
        'Do you have more experiences? Yes or No ')
    if has_more_experiences.lower() == 'yes':
        p = document.add_paragraph()

        company = input('Enter company ')
        from_date = input('From Date ')
        to_date = input('To Date ')

        p.add_run(company + ' ').bold = True
        p.add_run(from_date + '-' + to_date + '\n').italic = True

        experience_details = input(
            'Describe what you did at ' + company + ' ')
        p.add_run(experience_details)
    else:
        break

# hobbies
document.add_heading('Hobbies')
hobby = input('Enter a hobby of yours')
p = document.add_paragraph(hobby)
p.style = 'List Bullet'

# more hobbies
while True:
    has_more_hobbies = input('Do you have anymore hobbies? Yes or No ')
    if has_more_hobbies.lower() == 'yes':
        hobby = input('Enter a hobby of yours ')
        p = document.add_paragraph(hobby)
        p.style = 'List Bullet'

    else:
        break

# skills
document.add_heading('Skills')
skill = input('Enter skill ')
p = document.add_paragraph(skill)
p.style = 'List Bullet'

# more skills
while True:
    has_more_skills = input('Do you have more skills? Yes or No ')
    if has_more_skills.lower() == 'yes':
        skill = input('Enter skill ')
        p = document.add_paragraph(skill)
        p.style = 'List Bullet'

    else:
        break

# footer
section = document.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text = 'CV generated by James Brown. Generator made with Python by James Brown'

document.save('cv.docx')
